In [ ]:
import numpy as np
import scipy as sp
import pandas as pd

from pandas.plotting import scatter_matrix
import seaborn as sns
import matplotlib.pyplot as plt


from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score

from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import make_pipeline as make_imb_pipeline
from imblearn.under_sampling import RepeatedEditedNearestNeighbours
from imblearn.under_sampling import EditedNearestNeighbours

from keras.models import Sequential
from keras.layers import Dense, Dropout
from scikeras.wrappers import KerasClassifier

from pympler import tracker
import pickle

In [1]:
import pandas as pd


In [2]:
df = pd.read_csv('evaluation round1.csv')

In [3]:
df.shape

(12604600, 69)

In [2]:
import tensorflow as tf
print(tf.__version__)

2.16.1


### Loading data

In [ ]:
df=pd.read_csv("train.csv")

In [3]:
df.head()

ind_recommended  activation  customer_digital_activity_04  \
0                0           0                           NaN   
1                0           0                           NaN   
2                0           0                           NaN   
3                0           0                           NaN   
4                1           0                           NaN   

   customer_spend_01  customer_industry_spend_01  customer_industry_spend_02  \
0         107.215862                   26.686594                        74.0   
1          35.552000                   50.928261                         3.0   
2          31.623103                   48.837872                        19.0   
3         112.277391                         NaN                         NaN   
4         448.427273                         NaN                         NaN   

   customer_industry_spend_03  customer_industry_spend_04  \
0                     3682.75                       138.0   
1                     1171.35                        23.0   
2                     2295.38                        47.0   
3                         NaN                         NaN   
4                         NaN                         NaN   

   customer_industry_spend_05  customer_spend_02  ...  merchant_spend_09  \
0                       111.0               14.0  ...            49466.0   
1                        17.0                2.0  ...             3638.0   
2                        42.0               11.0  ...             3912.0   
3                         NaN               16.0  ...            28919.0   
4                         NaN                5.0  ...             1086.0   

   merchant_profile_03  customer_digital_activity_01  merchant_spend_10  \
0              65923.0                      0.000000             29.180   
1               7801.0                      0.419355             28.465   
2              12868.0                      0.836364            421.500   
3              23553.0                      0.952381             50.000   
4                308.0                      0.754386             69.509   

   customer_profile_03  customer_digital_activity_02  customer_profile_04  \
0            58.434969                     32.500000                 86.0   
1             5.392089                      7.000000                125.0   
2            33.780445                      0.000000                180.0   
3            37.340085                     28.666667                134.0   
4            77.794164                     15.000000                114.0   

   distance_05  customer  merchant  
0    15.856826    168972    152285  
1     6.998555    212404     39032  
2     1.753009    225178      7439  
3     9.000063    183948    485069  
4     1.767939    210107    536004  

[5 rows x 71 columns]

In [4]:
size = df.shape
valid_counts = df.count()

column_of_interest = 'activation'

# Get the unique values and the number of unique values
unique_values = df[column_of_interest].unique()
value_counts = df[column_of_interest].value_counts()

print("Value counts for column '{}':\n{}".format(column_of_interest, value_counts))

Value counts for column 'activation':
activation
0    12159962
1       70016
Name: count, dtype: int64


### Preprocessing data


#### Drop rows
major issue of missing values in multiple entires. if eliminate all NA values, the data will have small size\
drop rows with more than half the features being NA 

In [5]:
drop_na  = df.dropna(thresh=len(df.columns)/2)
del df # save memories
print ('After dropping those with more than half the data dimension being na, the size is:', drop_na.shape)

After dropping those with more than half the data dimension being na, the size is: (7822511, 71)


#### Drop columns
customer_merchant_01, customer_merchant_02, customer_digital_activity_01, 02, 07, 08, 09, 18\
Assumption: they do not contribute significantly to the recommendation

In [6]:
y_train = drop_na.activation
columns_to_drop = []
for col in drop_na.columns:
    if drop_na[col].count() < size[0]*0.1:
        columns_to_drop.append(col)

data_train = drop_na.drop(columns_to_drop, axis=1)


del drop_na


In [7]:
X_train = data_train.drop(['ind_recommended', 'activation'],axis=1)

del data_train

#### Imbalanced UnderSampling: 
Choice of undersampling technique: Random Undersampling\
https://imbalanced-learn.org/stable/under_sampling.html

In [8]:
#   EditedN
##  enn = EditedNearestNeighbours()
#   X_resampled, y_resampled = enn.fit_resample(X_train, y_train)

##  renn = RepeatedEditedNearestNeighbours()
#   X_resampled, y_resampled = renn.fit_resample(X_train, y_train)
rus = RandomUnderSampler()
X_resampled, y_resampled = rus.fit_resample(X_train, y_train)

class_count = y_resampled.value_counts()
X_resampled.shape, class_count

((134120, 61),
 activation
 0    67060
 1    67060
 Name: count, dtype: int64)

In [9]:
knn_imputer = KNNImputer(n_neighbors=5)  # Set the number of neighbors as per your dataset
X_imputed = knn_imputer.fit_transform(X_resampled)

In [11]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_imputed, y_resampled, test_size=0.2, random_state=42)

In [10]:
nan_count = np.isnan(X_imputed).sum()
print("Number of NaN values in the array: ", nan_count)

Number of NaN values in the array:  0


#### Serialize for training data use

In [12]:
# serialize the train and test data ready for continued use training models 
data = {'X_train': X_train, 'X_test': X_test, 'y_train': y_train, 'y_test': y_test}
with open('amex_traintest.pickle', 'wb') as file:
    pickle.dump(data, file)

In [3]:
# load the data (run this everytime the kernel is restarted)
with open('amex_traintest.pickle', 'rb') as file:
    data = pickle.load(file)
    X_train = data['X_train']
    X_test = data['X_test']
    y_train = data['y_train']
    y_test = data['y_test']

    y_train = y_train.values
    y_test = y_test.values

In [4]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((107296, 61), (26824, 61), (107296,), (26824,))

In [ ]:
# Assuming X_resampled is the undersampled feature matrix

# Define the parameter grid for number of neighbors
param_grid = {'n_neighbors': [3, 5, 7, 9, 11]}  

# Instantiate the KNNImputer
knn_imputer = KNNImputer()

# Perform grid search to find the optimal number of neighbors
grid_search = GridSearchCV(knn_imputer, param_grid, scoring='roc_auc', cv=5)
grid_search.fit(X_resampled, y_resampled)

# Best number of neighbors
best_neighbors = grid_search.best_params_['n_neighbors']
print(f"Optimal number of neighbors: {best_neighbors}")

In [5]:
def scale_features(X_train, X_test):
    sc = StandardScaler()
    X_train_ss = sc.fit_transform(X_train)
    X_test_ss = sc.transform(X_test)
    return X_train_ss, X_test_ss
X_train_ss, X_test_ss = scale_features(X_train, X_test)

### Binary Classifier

#### Random Forest

In [14]:
## RandomForest Classifier
RF = RandomForestClassifier(random_state=42)
RF.fit(X_train, y_train)
y_pred_test_rf = cross_val_predict(RF, X_test, y_test, cv=5, method='predict')
roc_auc_score(y_test, y_pred_test_rf), confusion_matrix(y_test, y_pred_test_rf)

(0.8137424902561045,
 array([[10925,  2577],
        [ 2420, 10902]], dtype=int64))

#### SVC

In [15]:
# SVC: non standardized
svm = SVC(random_state=42)
svm.fit(X_train, y_train)
y_pred_test_svm = cross_val_predict(svm, X_test, y_test, cv=5, method = "predict")
roc_auc_score(y_test, y_pred_test_svm), confusion_matrix(y_test, y_pred_test_svm)


(0.7036878454522221,
 array([[9597, 3905],
        [4042, 9280]], dtype=int64))

In [6]:
# SVC: distanced based so we use X_train_ss
svm = SVC(random_state=42)
svm.fit(X_train_ss, y_train)
y_pred_test_svm = cross_val_predict(svm, X_test_ss, y_test, cv=5, method = "predict")
roc_auc_score(y_test, y_pred_test_svm), confusion_matrix(y_test, y_pred_test_svm)

(0.8010196591113704,
 array([[10699,  2803],
        [ 2536, 10786]], dtype=int64))

#### KNN

In [25]:
# KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(X_train, y_train)  
y_pred_test_knn = cross_val_predict(knn, X_test, y_test, cv=5, method='predict')
roc_auc_score(y_test, y_pred_test_knn), confusion_matrix(y_test, y_pred_test_knn)

(0.654216762295648,
 array([[9155, 4347],
        [4924, 8398]], dtype=int64))

In [14]:
# KNN Classifier: Standardized
knn = KNeighborsClassifier(n_neighbors=5) 
knn.fit(X_train_ss, y_train)  
y_pred_test_knn = cross_val_predict(knn, X_test_ss, y_test, cv=5, method='predict')
roc_auc_score(y_test, y_pred_test_knn), confusion_matrix(y_test, y_pred_test_knn)

(0.7260558695302798,
 array([[9749, 3753],
        [3596, 9726]], dtype=int64))

#### Ensemble: Voting

In [7]:
# Voting Classifier with all exisiting classifier - hard voting
voting_clf = VotingClassifier(
    estimators=[
        #('lr', LogisticRegression(random_state=42)),
        ('rf', RandomForestClassifier(random_state=42)),
        ('svc', SVC(random_state=42)),
        ('knn', KNeighborsClassifier(n_neighbors=5))
    ]
)
voting_clf.fit(X_train_ss, y_train)

for name, clf in voting_clf.named_estimators_.items():
    print (name, "=", clf.score(X_test_ss, y_test))
voting_clf.score(X_test_ss, y_test)


rf = 0.821391291380853
svc = 0.8092752758723532
knn = 0.7385923053981509


0.8129287205487623

In [10]:
# Soft voting
voting_clf.voting = "soft"
voting_clf.named_estimators["svc"].probability = True
voting_clf.fit(X_train_ss, y_train)
voting_clf.score(X_test_ss, y_test)

0.81031911720847

#### RandomForest GridSearch

In [4]:
# Load the dataset and split into features and target variable
# Assuming X and y are the features and target variable

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'criterion': ['gini', 'entropy']
}

# Instantiate the Random Forest Classifier
rf = RandomForestClassifier()

# Perform Grid Search
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

# Retrieve the Best Parameters
best_params = grid_search.best_params_
best_estimator = grid_search.best_estimator_

# Evaluate the Model
y_pred = best_estimator.predict(X_test)
# Additional evaluation metrics and analysis

Fitting 5 folds for each of 72 candidates, totalling 360 fits


In [8]:
best_params, best_estimator

({'criterion': 'gini',
  'max_depth': None,
  'min_samples_split': 5,
  'n_estimators': 300},
 RandomForestClassifier(min_samples_split=5, n_estimators=300))

In [9]:
# serialize the best y, estimator, params ready for continued use training models 
params = {'y_pred': y_pred, 'best_estimator': best_estimator, 'best_params': best_params}
with open('amex_GridsearchRF.pickle', 'wb') as file:
    pickle.dump(params, file)

In [6]:
# RF: Best y, parameter, and estimator
roc_auc_score(y_test, y_pred), confusion_matrix(y_test, y_pred)

(0.823046399171187,
 array([[10933,  2569],
        [ 2180, 11142]], dtype=int64))

#### SVC GridSearchCV

In [11]:
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001],
    'kernel': ['rbf', 'linear', 'poly', 'sigmoid']
}

# Instantiate the Support Vector Classifier (SVC)
svc = SVC()

# Perform Grid Search
grid_search = GridSearchCV(estimator=svc, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train_ss, y_train)

# Retrieve the Best Parameters
best_params_svc = grid_search.best_params_
best_estimator_svc = grid_search.best_estimator_

# Evaluate the Model
y_pred_svc = best_estimator_svc.predict(X_test_ss)
# Additional evaluation metrics and analysis
roc_auc_score(y_test, y_pred_svc), confusion_matrix(y_test, y_pred_svc), best_params_svc, best_estimator_svc


Fitting 5 folds for each of 64 candidates, totalling 320 fits


### Neural Network

#### MLP Neural Network 

##### Non-Standardized

In [19]:
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline

mlp_clf = MLPClassifier(hidden_layer_sizes=[5], max_iter=10_000,
                        random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_clf)
pipeline.fit(X_train, y_train)
accuracy = pipeline.score(X_test, y_test)
accuracy

0.8101699970175962

##### Standardized

In [ ]:
mlp_clf = MLPClassifier(hidden_layer_sizes=[5], max_iter=10_000,
                        random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_clf)
pipeline.fit(X_train_ss, y_train)
accuracy = pipeline.score(X_test_ss, y_test)
accuracy

0.8101699970175962

#### Keras Tuner network

In [2]:
import keras_tuner as kt

def build_model(hp):
    n_hidden = hp.Int("n_hidden", min_value=0, max_value=30, default=2)
    n_neurons = hp.Int("n_neurons", min_value=16, max_value=800)
    learning_rate = hp.Float("learning_rate", min_value=1e-4, max_value=1e-2,
                             sampling="log")
    optimizer = hp.Choice("optimizer", values=["sgd", "adam"])
    if optimizer == "sgd":
        optimizer = tf.keras.optimizers.SGD(learning_rate=learning_rate)
    else:
        optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)

    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Flatten())
    for _ in range(n_hidden):
        model.add(tf.keras.layers.Dense(n_neurons, activation="relu"))
    model.add(tf.keras.layers.Dense(1, activation="sigmoid"))
    model.compile(loss="binary_crossentropy", optimizer=optimizer,
                  metrics=["accuracy"])
    return model

In [ ]:
random_search_tuner = kt.RandomSearch(
    build_model, objective="val_accuracy", max_trials=5, overwrite=True,
    directory="Amex Hackathon", project_name="recommendation", seed=42)
random_search_tuner.search(X_train_ss, y_train, epochs=100,
                           validation_data=(X_test_ss, y_test))

In [ ]:
top3_models = random_search_tuner.get_best_models(num_models=3)
best_model = top3_models[0]

In [ ]:
top3_params = random_search_tuner.get_best_hyperparameters(num_trials=3)
top3_params[0].values

In [ ]:
best_trial = random_search_tuner.oracle.get_best_trials(num_trials=1)[0]
best_trial.summary()

In [43]:
normalization_layer = tf.keras.layers.Normalization()
hidden_layer1 = tf.keras.layers.Dense(30, activation="relu")
hidden_layer2 = tf.keras.layers.Dense(30, activation="relu")
concat_layer = tf.keras.layers.Concatenate()
output_layer = tf.keras.layers.Dense(1, activation="sigmoid")

input_ = tf.keras.layers.Input(shape=X_train.shape[1:])
normalized = normalization_layer(input_)
hidden1 = hidden_layer1(normalized)
hidden2 = hidden_layer2(hidden1)
concat = concat_layer([normalized, hidden2])
output = output_layer(concat)

model_xxx = tf.keras.Model(inputs=[input_], outputs=[output])

In [44]:
optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
model_xxx.compile(loss="binary_crossentropy", optimizer=optimizer,
                  metrics=["accuracy"])
normalization_layer.adapt(X_train)
history = model_xxx.fit(X_train, y_train, epochs=20)
score = model_xxx.evaluate(X_test, y_test)


Epoch 1/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.6779 - loss: 3.0317
Epoch 2/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.7195 - loss: 1.5214
Epoch 3/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.7275 - loss: 0.9006
Epoch 4/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.7007 - loss: 1.0449
Epoch 5/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.6791 - loss: 1.0379
Epoch 6/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.7388 - loss: 0.7347
Epoch 7/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7497 - loss: 0.6611
Epoch 8/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7661 - loss: 0.6374
Epoch 9/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7717 - loss: 0.5894
Epoch 10/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - accuracy: 0.7499 - loss: 0.6764
Epoch 11/20
3353/3353 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.7622 - loss: 0.6217
Epoch 12/20
3353/3353 ━━━━━━━━